"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


# from setuptools import find_packages, setup  # noqa: H301

# NAME = "pyjama_client"
# VERSION = "0.0.1"
# # To install the library, run the following
# #
# # python setup.py install
# #
# # prerequisite: setuptools
# # http://pypi.python.org/pypi/setuptools

# REQUIRES = [
#     "urllib3 >= 1.25.3",
#     "python-dateutil",
# ]

# setup(
#     name=NAME,
#     version=VERSION,
#     description="Jama REST API",
#     author="support@jamasoftware.com",
#     author_email="team@openapitools.org",
#     url="",
#     keywords=["OpenAPI", "OpenAPI-Generator", "Jama REST API"],
#     python_requires=">=3.6",
#     install_requires=REQUIRES,
#     packages=find_packages(exclude=["test", "tests"]),
#     include_package_data=True,
#     long_description="""\
#     This is the documentation for the Jama REST API.  # noqa: E501
#     """,
# )

from setuptools import setup

if __name__ == "__main__":
    setup()
