"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.pick_list import PickList

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["PickList"] = PickList
from pyjama.model.pick_list_data_wrapper import PickListDataWrapper


class TestPickListDataWrapper(unittest.TestCase):
    """PickListDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPickListDataWrapper(self):
        """Test PickListDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PickListDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
