"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.filter import Filter
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper

globals()["Filter"] = Filter
globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
from pyjama.model.filter_data_wrapper import FilterDataWrapper


class TestFilterDataWrapper(unittest.TestCase):
    """FilterDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterDataWrapper(self):
        """Test FilterDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilterDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
