"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper
from pyjama.model.pick_list_option import PickListOption

globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
globals()["PickListOption"] = PickListOption
from pyjama.model.pick_list_option_data_list_wrapper import (
    PickListOptionDataListWrapper,
)


class TestPickListOptionDataListWrapper(unittest.TestCase):
    """PickListOptionDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPickListOptionDataListWrapper(self):
        """Test PickListOptionDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PickListOptionDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
