"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.risk_rank_value_inbound_dto import RiskRankValueInboundDTO

globals()["RiskRankValueInboundDTO"] = RiskRankValueInboundDTO
from pyjama.model.risk_field_config_inbound_dto import RiskFieldConfigInboundDTO


class TestRiskFieldConfigInboundDTO(unittest.TestCase):
    """RiskFieldConfigInboundDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRiskFieldConfigInboundDTO(self):
        """Test RiskFieldConfigInboundDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RiskFieldConfigInboundDTO()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
