"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.attachment import Attachment
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper

globals()["Attachment"] = Attachment
globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
from pyjama.model.attachment_data_wrapper import AttachmentDataWrapper


class TestAttachmentDataWrapper(unittest.TestCase):
    """AttachmentDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachmentDataWrapper(self):
        """Test AttachmentDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachmentDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
