"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.abstract_item import AbstractItem
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper

globals()["AbstractItem"] = AbstractItem
globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
from pyjama.model.abstract_item_data_wrapper import AbstractItemDataWrapper


class TestAbstractItemDataWrapper(unittest.TestCase):
    """AbstractItemDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAbstractItemDataWrapper(self):
        """Test AbstractItemDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AbstractItemDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
