"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.request_comment_body import RequestCommentBody
from pyjama.model.request_comment_location import RequestCommentLocation

globals()["RequestCommentBody"] = RequestCommentBody
globals()["RequestCommentLocation"] = RequestCommentLocation
from pyjama.model.request_comment import RequestComment


class TestRequestComment(unittest.TestCase):
    """RequestComment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestComment(self):
        """Test RequestComment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestComment()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
