"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.risk_update_dto import RiskUpdateDTO


class TestRiskUpdateDTO(unittest.TestCase):
    """RiskUpdateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRiskUpdateDTO(self):
        """Test RiskUpdateDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RiskUpdateDTO()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
