"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.duplicate_config import DuplicateConfig


class TestDuplicateConfig(unittest.TestCase):
    """DuplicateConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDuplicateConfig(self):
        """Test DuplicateConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DuplicateConfig()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
