"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.page_info import PageInfo

globals()["PageInfo"] = PageInfo
from pyjama.model.rest_response import RestResponse


class TestRestResponse(unittest.TestCase):
    """RestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRestResponse(self):
        """Test RestResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RestResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
