"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.risk_field_config_inbound_dto import RiskFieldConfigInboundDTO

globals()["RiskFieldConfigInboundDTO"] = RiskFieldConfigInboundDTO
from pyjama.model.risk_analysis_section_inbound_dto import RiskAnalysisSectionInboundDTO


class TestRiskAnalysisSectionInboundDTO(unittest.TestCase):
    """RiskAnalysisSectionInboundDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRiskAnalysisSectionInboundDTO(self):
        """Test RiskAnalysisSectionInboundDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RiskAnalysisSectionInboundDTO()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
