"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.testcycles_api import TestcyclesApi  # noqa: E501


class TestTestcyclesApi(unittest.TestCase):
    """TestcyclesApi unit test stubs"""

    def setUp(self):
        self.api = TestcyclesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_test_cycle(self):
        """Test case for delete_test_cycle

        Delete the test cycle with the specified ID, including the test runs in the test cycle  # noqa: E501
        """
        pass

    def test_get_test_cycle(self):
        """Test case for get_test_cycle

        Get the test cycle with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_cycle_test_group(self):
        """Test case for get_test_cycle_test_group

        Get the test cycle test group for the test cycle with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_cycle_test_runs(self):
        """Test case for get_test_cycle_test_runs

        Get all test runs for the test cycle with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_cycle_version(self):
        """Test case for get_test_cycle_version

        Get the  snapshot of the test cycle at the specified version  # noqa: E501
        """
        pass

    def test_get_test_cycle_versioned(self):
        """Test case for get_test_cycle_versioned

        Get the numbered version for the item with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_cycle_versions(self):
        """Test case for get_test_cycle_versions

        Get all versions for the item with the specified ID  # noqa: E501
        """
        pass

    def test_patch_test_cycle(self):
        """Test case for patch_test_cycle

        Update the test cycle with the specified ID, including regenerating the test runs in the test cycle  # noqa: E501
        """
        pass

    def test_update_test_cycle(self):
        """Test case for update_test_cycle

        Update the test cycle with the specified ID, including regenerating the test runs in the test cycle  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
