"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.relationshiptypes_api import RelationshiptypesApi  # noqa: E501


class TestRelationshiptypesApi(unittest.TestCase):
    """RelationshiptypesApi unit test stubs"""

    def setUp(self):
        self.api = RelationshiptypesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_relationship_type(self):
        """Test case for get_relationship_type

        Get the relationship type with the specified ID  # noqa: E501
        """
        pass

    def test_get_relationship_types(self):
        """Test case for get_relationship_types

        Get all relationship types  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
