"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.version import Version

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["Version"] = Version
from pyjama.model.version_data_wrapper import VersionDataWrapper


class TestVersionDataWrapper(unittest.TestCase):
    """VersionDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionDataWrapper(self):
        """Test VersionDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
