"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.versioned_test_cycle import VersionedTestCycle

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["VersionedTestCycle"] = VersionedTestCycle
from pyjama.model.versioned_test_cycle_data_wrapper import VersionedTestCycleDataWrapper


class TestVersionedTestCycleDataWrapper(unittest.TestCase):
    """VersionedTestCycleDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionedTestCycleDataWrapper(self):
        """Test VersionedTestCycleDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionedTestCycleDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
