"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.risk_rank_value_inbound_dto import RiskRankValueInboundDTO


class TestRiskRankValueInboundDTO(unittest.TestCase):
    """RiskRankValueInboundDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRiskRankValueInboundDTO(self):
        """Test RiskRankValueInboundDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RiskRankValueInboundDTO()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
