"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.harm_inbound_dto import HarmInboundDTO

globals()["HarmInboundDTO"] = HarmInboundDTO
from pyjama.model.risk_inbound_dto import RiskInboundDTO


class TestRiskInboundDTO(unittest.TestCase):
    """RiskInboundDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRiskInboundDTO(self):
        """Test RiskInboundDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RiskInboundDTO()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
