"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.pick_list_option import PickListOption

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["PickListOption"] = PickListOption
from pyjama.model.pick_list_option_data_wrapper import PickListOptionDataWrapper


class TestPickListOptionDataWrapper(unittest.TestCase):
    """PickListOptionDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPickListOptionDataWrapper(self):
        """Test PickListOptionDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PickListOptionDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
