"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.users_api import UsersApi  # noqa: E501


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user(self):
        """Test case for add_user

        Create a new user  # noqa: E501
        """
        pass

    def test_get_current_user(self):
        """Test case for get_current_user

        Gets the current user  # noqa: E501
        """
        pass

    def test_get_current_user_favorite_filters(self):
        """Test case for get_current_user_favorite_filters

        Gets the current user's favorite filters  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get the user with the specified ID  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        Get all users  # noqa: E501
        """
        pass

    def test_put_user(self):
        """Test case for put_user

        Update the user with the specified ID  # noqa: E501
        """
        pass

    def test_set_active_status(self):
        """Test case for set_active_status

        Update the active status for the user with the specified ID  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
