"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.allowed_resource import AllowedResource

globals()["AllowedResource"] = AllowedResource
from pyjama.model.versioned_test_cycle import VersionedTestCycle


class TestVersionedTestCycle(unittest.TestCase):
    """VersionedTestCycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionedTestCycle(self):
        """Test VersionedTestCycle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionedTestCycle()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
