"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.abstract_item import AbstractItem
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper

globals()["AbstractItem"] = AbstractItem
globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
from pyjama.model.abstract_item_data_list_wrapper import AbstractItemDataListWrapper


class TestAbstractItemDataListWrapper(unittest.TestCase):
    """AbstractItemDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAbstractItemDataListWrapper(self):
        """Test AbstractItemDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AbstractItemDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
