"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.relationship import Relationship


class TestRelationship(unittest.TestCase):
    """Relationship unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRelationship(self):
        """Test Relationship"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Relationship()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
