"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.request_parent import RequestParent

globals()["RequestParent"] = RequestParent
from pyjama.model.request_location import RequestLocation


class TestRequestLocation(unittest.TestCase):
    """RequestLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestLocation(self):
        """Test RequestLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestLocation()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
