"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper
from pyjama.model.relationship import Relationship

globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
globals()["Relationship"] = Relationship
from pyjama.model.relationship_data_list_wrapper import RelationshipDataListWrapper


class TestRelationshipDataListWrapper(unittest.TestCase):
    """RelationshipDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRelationshipDataListWrapper(self):
        """Test RelationshipDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RelationshipDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
