"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.risk_analysis_section_inbound_dto import RiskAnalysisSectionInboundDTO

globals()["RiskAnalysisSectionInboundDTO"] = RiskAnalysisSectionInboundDTO
from pyjama.model.risk_analysis_update_dto import RiskAnalysisUpdateDTO


class TestRiskAnalysisUpdateDTO(unittest.TestCase):
    """RiskAnalysisUpdateDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRiskAnalysisUpdateDTO(self):
        """Test RiskAnalysisUpdateDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RiskAnalysisUpdateDTO()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
