"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.request_patch_operation import RequestPatchOperation


class TestRequestPatchOperation(unittest.TestCase):
    """RequestPatchOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestPatchOperation(self):
        """Test RequestPatchOperation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestPatchOperation()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
