"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.request_move_parent import RequestMoveParent


class TestRequestMoveParent(unittest.TestCase):
    """RequestMoveParent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestMoveParent(self):
        """Test RequestMoveParent"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestMoveParent()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
