"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.usergroups_api import UsergroupsApi  # noqa: E501


class TestUsergroupsApi(unittest.TestCase):
    """UsergroupsApi unit test stubs"""

    def setUp(self):
        self.api = UsergroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user_group(self):
        """Test case for add_user_group

        Create a new user group  # noqa: E501
        """
        pass

    def test_add_user_to_group(self):
        """Test case for add_user_to_group

        Add an existing user to the user group with the specified ID  # noqa: E501
        """
        pass

    def test_delete_user_group(self):
        """Test case for delete_user_group

        Delete the user group with the specified ID  # noqa: E501
        """
        pass

    def test_get_group(self):
        """Test case for get_group

        Get the user group with the specified ID  # noqa: E501
        """
        pass

    def test_get_group_users(self):
        """Test case for get_group_users

        Get all users for the user group with the specified ID  # noqa: E501
        """
        pass

    def test_get_user_groups(self):
        """Test case for get_user_groups

        Get all user groups  # noqa: E501
        """
        pass

    def test_remove_user_from_group(self):
        """Test case for remove_user_from_group

        Remove an existing user from the user group with the specified ID  # noqa: E501
        """
        pass

    def test_update_user_group(self):
        """Test case for update_user_group

        Update the user group with the specified ID  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
