"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.versioned_attachment import VersionedAttachment

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["VersionedAttachment"] = VersionedAttachment
from pyjama.model.versioned_attachment_data_wrapper import (
    VersionedAttachmentDataWrapper,
)


class TestVersionedAttachmentDataWrapper(unittest.TestCase):
    """VersionedAttachmentDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionedAttachmentDataWrapper(self):
        """Test VersionedAttachmentDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionedAttachmentDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
