"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.work_status import WorkStatus

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["WorkStatus"] = WorkStatus
from pyjama.model.work_status_data_wrapper import WorkStatusDataWrapper


class TestWorkStatusDataWrapper(unittest.TestCase):
    """WorkStatusDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkStatusDataWrapper(self):
        """Test WorkStatusDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkStatusDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
