"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.user import User

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["User"] = User
from pyjama.model.user_data_wrapper import UserDataWrapper


class TestUserDataWrapper(unittest.TestCase):
    """UserDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDataWrapper(self):
        """Test UserDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
