"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper
from pyjama.model.version import Version

globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
globals()["Version"] = Version
from pyjama.model.version_data_list_wrapper import VersionDataListWrapper


class TestVersionDataListWrapper(unittest.TestCase):
    """VersionDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionDataListWrapper(self):
        """Test VersionDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
