"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.filter import Filter
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper

globals()["Filter"] = Filter
globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
from pyjama.model.filter_data_list_wrapper import FilterDataListWrapper


class TestFilterDataListWrapper(unittest.TestCase):
    """FilterDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterDataListWrapper(self):
        """Test FilterDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilterDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
