"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link


class TestLink(unittest.TestCase):
    """Link unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLink(self):
        """Test Link"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Link()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
