"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.page_info import PageInfo

globals()["PageInfo"] = PageInfo
from pyjama.model.abstract_rest_response import AbstractRestResponse


class TestAbstractRestResponse(unittest.TestCase):
    """AbstractRestResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAbstractRestResponse(self):
        """Test AbstractRestResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AbstractRestResponse()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
