"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.versioned_item import VersionedItem

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["VersionedItem"] = VersionedItem
from pyjama.model.versioned_item_data_wrapper import VersionedItemDataWrapper


class TestVersionedItemDataWrapper(unittest.TestCase):
    """VersionedItemDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionedItemDataWrapper(self):
        """Test VersionedItemDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionedItemDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
