"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.system_api import SystemApi  # noqa: E501


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_domains(self):
        """Test case for get_domains

        Get the current CORS domain whitelist  # noqa: E501
        """
        pass

    def test_set_domains(self):
        """Test case for set_domains

        Update CORS domain whitelist  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
