"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.abstractitems_api import AbstractitemsApi  # noqa: E501


class TestAbstractitemsApi(unittest.TestCase):
    """AbstractitemsApi unit test stubs"""

    def setUp(self):
        self.api = AbstractitemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_abstract_item(self):
        """Test case for get_abstract_item

        Get any item, test plan, test cycle, test run, or attachment with the specified ID  # noqa: E501
        """
        pass

    def test_get_abstract_item_version(self):
        """Test case for get_abstract_item_version

        Get the  snapshot of the item at the specified version  # noqa: E501
        """
        pass

    def test_get_abstract_item_versioned(self):
        """Test case for get_abstract_item_versioned

        Get the numbered version for the item with the specified ID  # noqa: E501
        """
        pass

    def test_get_abstract_item_versioned_relationships(self):
        """Test case for get_abstract_item_versioned_relationships

        Get all versioned relationships that were associated to the item at the specified time  # noqa: E501
        """
        pass

    def test_get_abstract_item_versions(self):
        """Test case for get_abstract_item_versions

        Get all versions for the item with the specified ID  # noqa: E501
        """
        pass

    def test_get_abstract_items(self):
        """Test case for get_abstract_items

        Search for items, test plans, test cycles, test runs, or attachments  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
