"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.item import Item
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper

globals()["Item"] = Item
globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
from pyjama.model.item_data_wrapper import ItemDataWrapper


class TestItemDataWrapper(unittest.TestCase):
    """ItemDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemDataWrapper(self):
        """Test ItemDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ItemDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
