"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.relationship_type import RelationshipType

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["RelationshipType"] = RelationshipType
from pyjama.model.relationship_type_data_wrapper import RelationshipTypeDataWrapper


class TestRelationshipTypeDataWrapper(unittest.TestCase):
    """RelationshipTypeDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRelationshipTypeDataWrapper(self):
        """Test RelationshipTypeDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RelationshipTypeDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
