"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.activity import Activity
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper

globals()["Activity"] = Activity
globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
from pyjama.model.activity_data_wrapper import ActivityDataWrapper


class TestActivityDataWrapper(unittest.TestCase):
    """ActivityDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityDataWrapper(self):
        """Test ActivityDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivityDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
