"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.versioned_test_plan import VersionedTestPlan

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["VersionedTestPlan"] = VersionedTestPlan
from pyjama.model.versioned_test_plan_data_wrapper import VersionedTestPlanDataWrapper


class TestVersionedTestPlanDataWrapper(unittest.TestCase):
    """VersionedTestPlanDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionedTestPlanDataWrapper(self):
        """Test VersionedTestPlanDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionedTestPlanDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
