"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.test_cycle_test_group import TestCycleTestGroup

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["TestCycleTestGroup"] = TestCycleTestGroup
from pyjama.model.test_cycle_test_group_data_wrapper import (
    TestCycleTestGroupDataWrapper,
)


class TestTestCycleTestGroupDataWrapper(unittest.TestCase):
    """TestCycleTestGroupDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestCycleTestGroupDataWrapper(self):
        """Test TestCycleTestGroupDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestCycleTestGroupDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
