"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper
from pyjama.model.versioned_relationship import VersionedRelationship

globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
globals()["VersionedRelationship"] = VersionedRelationship
from pyjama.model.versioned_relationship_data_list_wrapper import (
    VersionedRelationshipDataListWrapper,
)


class TestVersionedRelationshipDataListWrapper(unittest.TestCase):
    """VersionedRelationshipDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionedRelationshipDataListWrapper(self):
        """Test VersionedRelationshipDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionedRelationshipDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
