"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper
from pyjama.model.user import User

globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
globals()["User"] = User
from pyjama.model.user_data_list_wrapper import UserDataListWrapper


class TestUserDataListWrapper(unittest.TestCase):
    """UserDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserDataListWrapper(self):
        """Test UserDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
