"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.request_group_user import RequestGroupUser


class TestRequestGroupUser(unittest.TestCase):
    """RequestGroupUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestGroupUser(self):
        """Test RequestGroupUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RequestGroupUser()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
