"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper

globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
from pyjama.model.link_data_list_wrapper import LinkDataListWrapper


class TestLinkDataListWrapper(unittest.TestCase):
    """LinkDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkDataListWrapper(self):
        """Test LinkDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LinkDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
