"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.filter_field import FilterField
from pyjama.model.filter_query import FilterQuery

globals()["FilterField"] = FilterField
globals()["FilterQuery"] = FilterQuery
from pyjama.model.filter_rule import FilterRule


class TestFilterRule(unittest.TestCase):
    """FilterRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterRule(self):
        """Test FilterRule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilterRule()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
