"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.comments_api import CommentsApi  # noqa: E501


class TestCommentsApi(unittest.TestCase):
    """CommentsApi unit test stubs"""

    def setUp(self):
        self.api = CommentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_comment(self):
        """Test case for add_comment

        Create a new comment  # noqa: E501
        """
        pass

    def test_get_comment(self):
        """Test case for get_comment

        Get the comment with the specified ID  # noqa: E501
        """
        pass

    def test_get_comment_replies(self):
        """Test case for get_comment_replies

        Get all reply comments for the comment with the specified ID  # noqa: E501
        """
        pass

    def test_get_comments(self):
        """Test case for get_comments

        Get all comments viewable by the current user  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
