"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.baseline import Baseline
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper

globals()["Baseline"] = Baseline
globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
from pyjama.model.baseline_data_list_wrapper import BaselineDataListWrapper


class TestBaselineDataListWrapper(unittest.TestCase):
    """BaselineDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaselineDataListWrapper(self):
        """Test BaselineDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaselineDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
