"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.item_type import ItemType
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper

globals()["ItemType"] = ItemType
globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
from pyjama.model.item_type_data_wrapper import ItemTypeDataWrapper


class TestItemTypeDataWrapper(unittest.TestCase):
    """ItemTypeDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemTypeDataWrapper(self):
        """Test ItemTypeDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ItemTypeDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
