"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.collection_summary import CollectionSummary


class TestCollectionSummary(unittest.TestCase):
    """CollectionSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCollectionSummary(self):
        """Test CollectionSummary"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CollectionSummary()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
