"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper
from pyjama.model.workflow_transition import WorkflowTransition

globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
globals()["WorkflowTransition"] = WorkflowTransition
from pyjama.model.workflow_transition_data_list_wrapper import (
    WorkflowTransitionDataListWrapper,
)


class TestWorkflowTransitionDataListWrapper(unittest.TestCase):
    """WorkflowTransitionDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkflowTransitionDataListWrapper(self):
        """Test WorkflowTransitionDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkflowTransitionDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
