"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.work_step_status import WorkStepStatus

globals()["WorkStepStatus"] = WorkStepStatus
from pyjama.model.work_status import WorkStatus


class TestWorkStatus(unittest.TestCase):
    """WorkStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkStatus(self):
        """Test WorkStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkStatus()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
