"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.baseline_parent import BaselineParent

globals()["BaselineParent"] = BaselineParent
from pyjama.model.baseline_location import BaselineLocation


class TestBaselineLocation(unittest.TestCase):
    """BaselineLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaselineLocation(self):
        """Test BaselineLocation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaselineLocation()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
