"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.derived_data_failure import DerivedDataFailure

globals()["DerivedDataFailure"] = DerivedDataFailure
from pyjama.model.derived_data_health_details_report import (
    DerivedDataHealthDetailsReport,
)


class TestDerivedDataHealthDetailsReport(unittest.TestCase):
    """DerivedDataHealthDetailsReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDerivedDataHealthDetailsReport(self):
        """Test DerivedDataHealthDetailsReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DerivedDataHealthDetailsReport()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
