"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.risk_analysis_section_inbound_dto import RiskAnalysisSectionInboundDTO
from pyjama.model.risk_inbound_dto import RiskInboundDTO

globals()["RiskAnalysisSectionInboundDTO"] = RiskAnalysisSectionInboundDTO
globals()["RiskInboundDTO"] = RiskInboundDTO
from pyjama.model.risk_analysis_inbound_dto import RiskAnalysisInboundDTO


class TestRiskAnalysisInboundDTO(unittest.TestCase):
    """RiskAnalysisInboundDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRiskAnalysisInboundDTO(self):
        """Test RiskAnalysisInboundDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RiskAnalysisInboundDTO()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
