"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.picklistoptions_api import PicklistoptionsApi  # noqa: E501


class TestPicklistoptionsApi(unittest.TestCase):
    """PicklistoptionsApi unit test stubs"""

    def setUp(self):
        self.api = PicklistoptionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_picklist_option_id(self):
        """Test case for get_picklist_option_id

        Get the pick list option with the specified ID  # noqa: E501
        """
        pass

    def test_update_picklist_option(self):
        """Test case for update_picklist_option

        Update the pick list option with the specified ID  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
