"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.relationship import Relationship

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["Relationship"] = Relationship
from pyjama.model.relationship_data_wrapper import RelationshipDataWrapper


class TestRelationshipDataWrapper(unittest.TestCase):
    """RelationshipDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRelationshipDataWrapper(self):
        """Test RelationshipDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RelationshipDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
