"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.picklists_api import PicklistsApi  # noqa: E501


class TestPicklistsApi(unittest.TestCase):
    """PicklistsApi unit test stubs"""

    def setUp(self):
        self.api = PicklistsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_pick_list_option(self):
        """Test case for add_pick_list_option

        Create a new pick list option for the pick list with the specified ID  # noqa: E501
        """
        pass

    def test_get_pick_list(self):
        """Test case for get_pick_list

        Get the pick list with the specified ID  # noqa: E501
        """
        pass

    def test_get_pick_list_options(self):
        """Test case for get_pick_list_options

        Get all pick list options for the pick list with the specified ID  # noqa: E501
        """
        pass

    def test_get_pick_lists(self):
        """Test case for get_pick_lists

        Get all pick lists  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
