"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.item_type_field import ItemTypeField


class TestItemTypeField(unittest.TestCase):
    """ItemTypeField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemTypeField(self):
        """Test ItemTypeField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ItemTypeField()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
