"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.attachment import Attachment
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper

globals()["Attachment"] = Attachment
globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
from pyjama.model.attachment_data_list_wrapper import AttachmentDataListWrapper


class TestAttachmentDataListWrapper(unittest.TestCase):
    """AttachmentDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttachmentDataListWrapper(self):
        """Test AttachmentDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AttachmentDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
