"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.allowed_resource import AllowedResource

globals()["AllowedResource"] = AllowedResource
from pyjama.model.versioned_test_run import VersionedTestRun


class TestVersionedTestRun(unittest.TestCase):
    """VersionedTestRun unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVersionedTestRun(self):
        """Test VersionedTestRun"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VersionedTestRun()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
