"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.testplans_api import TestplansApi  # noqa: E501


class TestTestplansApi(unittest.TestCase):
    """TestplansApi unit test stubs"""

    def setUp(self):
        self.api = TestplansApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_test_group(self):
        """Test case for add_test_group

        Create a new test group to the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_add_test_plan_attachment(self):
        """Test case for add_test_plan_attachment

        Add an existing attachment to the item with the specified ID  # noqa: E501
        """
        pass

    def test_add_test_plan_link(self):
        """Test case for add_test_plan_link

        Create a new link for the item with the specified ID  # noqa: E501
        """
        pass

    def test_add_test_plan_tag(self):
        """Test case for add_test_plan_tag

        Add an existing tag to the item with the specified ID  # noqa: E501
        """
        pass

    def test_create_test_cycle(self):
        """Test case for create_test_cycle

        Create a new test cycle  # noqa: E501
        """
        pass

    def test_create_test_plan(self):
        """Test case for create_test_plan

        Create a new test plan  # noqa: E501
        """
        pass

    def test_delete_test_case(self):
        """Test case for delete_test_case

        Remove an existing test case from the test group  # noqa: E501
        """
        pass

    def test_delete_test_group(self):
        """Test case for delete_test_group

        Delete the test group with the specified ID  # noqa: E501
        """
        pass

    def test_delete_test_plan(self):
        """Test case for delete_test_plan

        Delete the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_delete_test_plan_link(self):
        """Test case for delete_test_plan_link

        Delete the link with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_case(self):
        """Test case for get_test_case

        Get the test case with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_cases(self):
        """Test case for get_test_cases

        Get all test cases associated with the test group with the specified ID in a test plan  # noqa: E501
        """
        pass

    def test_get_test_group(self):
        """Test case for get_test_group

        Get the test group with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_groups(self):
        """Test case for get_test_groups

        Get all test groups for the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan(self):
        """Test case for get_test_plan

        Get the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_activities(self):
        """Test case for get_test_plan_activities

        Get all activities for the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_attachments(self):
        """Test case for get_test_plan_attachments

        Get all attachments for the item with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_comments(self):
        """Test case for get_test_plan_comments

        Get all comments for the item with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_downstream_related(self):
        """Test case for get_test_plan_downstream_related

        Get all downstream related items for the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_downstream_relationships(self):
        """Test case for get_test_plan_downstream_relationships

        Get all downstream relationships for the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_link(self):
        """Test case for get_test_plan_link

        Get the link with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_links(self):
        """Test case for get_test_plan_links

        Get all links for the item with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_lock(self):
        """Test case for get_test_plan_lock

        Get the locked state, last locked date, and last locked by user for the item with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_tag(self):
        """Test case for get_test_plan_tag

        Get the tag with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_tags(self):
        """Test case for get_test_plan_tags

        Get all tags for the item with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_test_cycles(self):
        """Test case for get_test_plan_test_cycles

        Get all test cycles for the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_upstream_related(self):
        """Test case for get_test_plan_upstream_related

        Get all upstream related items for the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_upstream_relationships(self):
        """Test case for get_test_plan_upstream_relationships

        Get all upstream relationships for the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plan_version(self):
        """Test case for get_test_plan_version

        Get the  snapshot of the test plan at the specified version  # noqa: E501
        """
        pass

    def test_get_test_plan_versions(self):
        """Test case for get_test_plan_versions

        Get all versions for the item with the specified ID  # noqa: E501
        """
        pass

    def test_get_test_plans(self):
        """Test case for get_test_plans

        Get all test plans in the project with the specified ID  # noqa: E501
        """
        pass

    def test_get_version_on_item4(self):
        """Test case for get_version_on_item4

        Get the numbered version for the item with the specified ID  # noqa: E501
        """
        pass

    def test_patch_test_plan(self):
        """Test case for patch_test_plan

        Update the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_post_test_case(self):
        """Test case for post_test_case

        Add an existing test case to the test group with the specified ID  # noqa: E501
        """
        pass

    def test_remove_attachment_from_test_plan(self):
        """Test case for remove_attachment_from_test_plan

        Remove an existing attachment from the item  # noqa: E501
        """
        pass

    def test_remove_test_plans_tag_from_item(self):
        """Test case for remove_test_plans_tag_from_item

        Remove an existing tag from the item with the specified ID  # noqa: E501
        """
        pass

    def test_toggle_archived_status(self):
        """Test case for toggle_archived_status

        Update the archived status of the test plan  # noqa: E501
        """
        pass

    def test_update_test_group(self):
        """Test case for update_test_group

        Update the test group with the specified ID  # noqa: E501
        """
        pass

    def test_update_test_plan(self):
        """Test case for update_test_plan

        Update the test plan with the specified ID  # noqa: E501
        """
        pass

    def test_update_test_plan_link(self):
        """Test case for update_test_plan_link

        Update the link with the specified ID  # noqa: E501
        """
        pass

    def test_update_test_plan_lock(self):
        """Test case for update_test_plan_lock

        Update the locked state of the item with the specified ID  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
