"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.derived_data_health_details_report import (
    DerivedDataHealthDetailsReport,
)

globals()["DerivedDataHealthDetailsReport"] = DerivedDataHealthDetailsReport
from pyjama.model.derived_data_health_report import DerivedDataHealthReport


class TestDerivedDataHealthReport(unittest.TestCase):
    """DerivedDataHealthReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDerivedDataHealthReport(self):
        """Test DerivedDataHealthReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DerivedDataHealthReport()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
