"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.test_run_generation_config import TestRunGenerationConfig


class TestTestRunGenerationConfig(unittest.TestCase):
    """TestRunGenerationConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestRunGenerationConfig(self):
        """Test TestRunGenerationConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestRunGenerationConfig()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
