"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.baseline_origin import BaselineOrigin

globals()["BaselineOrigin"] = BaselineOrigin
from pyjama.model.baseline import Baseline


class TestBaseline(unittest.TestCase):
    """Baseline unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseline(self):
        """Test Baseline"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Baseline()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
