"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.filter_field import FilterField


class TestFilterField(unittest.TestCase):
    """FilterField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFilterField(self):
        """Test FilterField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FilterField()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
