"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.baseline_item import BaselineItem
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper

globals()["BaselineItem"] = BaselineItem
globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
from pyjama.model.baseline_item_data_list_wrapper import BaselineItemDataListWrapper


class TestBaselineItemDataListWrapper(unittest.TestCase):
    """BaselineItemDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaselineItemDataListWrapper(self):
        """Test BaselineItemDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BaselineItemDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
