"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.test_group import TestGroup

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["TestGroup"] = TestGroup
from pyjama.model.test_group_data_wrapper import TestGroupDataWrapper


class TestTestGroupDataWrapper(unittest.TestCase):
    """TestGroupDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestGroupDataWrapper(self):
        """Test TestGroupDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestGroupDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
