"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.link import Link
from pyjama.model.meta_wrapper import MetaWrapper
from pyjama.model.tag import Tag

globals()["Link"] = Link
globals()["MetaWrapper"] = MetaWrapper
globals()["Tag"] = Tag
from pyjama.model.tag_data_wrapper import TagDataWrapper


class TestTagDataWrapper(unittest.TestCase):
    """TagDataWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagDataWrapper(self):
        """Test TagDataWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TagDataWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
