"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import unittest

import pyjama
from pyjama.api.filters_api import FiltersApi  # noqa: E501


class TestFiltersApi(unittest.TestCase):
    """FiltersApi unit test stubs"""

    def setUp(self):
        self.api = FiltersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_filter(self):
        """Test case for get_filter

        Get the filter with the specified ID  # noqa: E501
        """
        pass

    def test_get_filter_results(self):
        """Test case for get_filter_results

        Get all result items for the filter with the specified ID  # noqa: E501
        """
        pass

    def test_get_filters(self):
        """Test case for get_filters

        Get all filters viewable by the current user  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
