"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.activity import Activity
from pyjama.model.link import Link
from pyjama.model.meta_list_wrapper import MetaListWrapper

globals()["Activity"] = Activity
globals()["Link"] = Link
globals()["MetaListWrapper"] = MetaListWrapper
from pyjama.model.activity_data_list_wrapper import ActivityDataListWrapper


class TestActivityDataListWrapper(unittest.TestCase):
    """ActivityDataListWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActivityDataListWrapper(self):
        """Test ActivityDataListWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActivityDataListWrapper()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
