"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pyjama
from pyjama.model.item_type_widget import ItemTypeWidget


class TestItemTypeWidget(unittest.TestCase):
    """ItemTypeWidget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testItemTypeWidget(self):
        """Test ItemTypeWidget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ItemTypeWidget()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
