"""
    Jama REST API

    This is the documentation for the Jama REST API.  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from ..exceptions import ApiAttributeError
from ..model_utils import ApiTypeError  # noqa: F401
from ..model_utils import (
    ModelComposed,
    ModelNormal,
    ModelSimple,
    OpenApiModel,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


def lazy_import():
    from ..model.filter_field import FilterField
    from ..model.filter_query import FilterQuery

    globals()["FilterField"] = FilterField
    globals()["FilterQuery"] = FilterQuery


class FilterRule(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ("operator",): {
            "GROUP_OR": "GROUP_OR",
            "GROUP_AND": "GROUP_AND",
            "OR": "OR",
            "AND": "AND",
            "EQUALS": "EQUALS",
            "EQUALS_DATE": "EQUALS_DATE",
            "EQUALS_MULTI": "EQUALS_MULTI",
            "NOT_EQUALS": "NOT_EQUALS",
            "NOT_EQUALS_DATE": "NOT_EQUALS_DATE",
            "NOT_EQUALS_MULTI": "NOT_EQUALS_MULTI",
            "GREATER_THAN": "GREATER_THAN",
            "GREATER_THAN_DATE": "GREATER_THAN_DATE",
            "LESS_THAN": "LESS_THAN",
            "LESS_THAN_DATE": "LESS_THAN_DATE",
            "IN": "IN",
            "IS_TRUE": "IS_TRUE",
            "IS_FALSE": "IS_FALSE",
            "CONTAINS": "CONTAINS",
            "CONTAINS_WORD": "CONTAINS_WORD",
            "NOT_CONTAINS": "NOT_CONTAINS",
            "NOT_CONTAINS_WORD": "NOT_CONTAINS_WORD",
            "IS_ASSOCIATED_ITEM": "IS_ASSOCIATED_ITEM",
            "IS_ASSOCIATED_SUSPECT_ITEM": "IS_ASSOCIATED_SUSPECT_ITEM",
            "IS_ASSOCIATED_NOT_SUSPECT_ITEM": "IS_ASSOCIATED_NOT_SUSPECT_ITEM",
            "IS_BETWEEN": "IS_BETWEEN",
            "HAS_ALL": "HAS_ALL",
            "HAS_NONE": "HAS_NONE",
            "IS_DIRECTLY_UNDER": "IS_DIRECTLY_UNDER",
            "IS_UNDER": "IS_UNDER",
            "IS_CURRENT_USER": "IS_CURRENT_USER",
            "IS_EMPTY": "IS_EMPTY",
            "IS_NOT_EMPTY": "IS_NOT_EMPTY",
            "IS_NOT_DIRECTLY_UNDER": "IS_NOT_DIRECTLY_UNDER",
            "IS_UNDER_OR_EQUAL": "IS_UNDER_OR_EQUAL",
            "IS_NOT_UNDER": "IS_NOT_UNDER",
            "LOCATION_IS": "LOCATION_IS",
            "TEST_CENTER_RELATE": "TEST_CENTER_RELATE",
            "SHARED_WITH": "SHARED_WITH",
            "NOT_SHARED_WITH": "NOT_SHARED_WITH",
            "IS_WITHIN_LAST": "IS_WITHIN_LAST",
            "IS_DATE_TIME_BETWEEN": "IS_DATE_TIME_BETWEEN",
        },
    }

    validations = {}

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (
            bool,
            date,
            datetime,
            dict,
            float,
            int,
            list,
            str,
            none_type,
        )  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            "field": (FilterField,),  # noqa: E501
            "operator": (str,),  # noqa: E501
            "values": ([str],),  # noqa: E501
            "item_type": (int,),  # noqa: E501
            "sub_query": (FilterQuery,),  # noqa: E501
            "rules": ([FilterRule],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None

    attribute_map = {
        "field": "field",  # noqa: E501
        "operator": "operator",  # noqa: E501
        "values": "values",  # noqa: E501
        "item_type": "itemType",  # noqa: E501
        "sub_query": "subQuery",  # noqa: E501
        "rules": "rules",  # noqa: E501
    }

    read_only_vars = {}

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(
        cls, field, operator, values, item_type, sub_query, rules, *args, **kwargs
    ):  # noqa: E501
        """FilterRule - a model defined in OpenAPI

        Args:
            field (FilterField):
            operator (str):
            values ([str]):
            item_type (int): ID of an item type
            sub_query (FilterQuery):
            rules ([FilterRule]):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", True)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (args, self.__class__.__name__,),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.field = field
        self.operator = operator
        self.values = values
        self.item_type = item_type
        self.sub_query = sub_query
        self.rules = rules
        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set(
        [
            "_data_store",
            "_check_type",
            "_spec_property_naming",
            "_path_to_item",
            "_configuration",
            "_visited_composed_classes",
        ]
    )

    @convert_js_args_to_python_args
    def __init__(
        self, field, operator, values, item_type, sub_query, rules, *args, **kwargs
    ):  # noqa: E501
        """FilterRule - a model defined in OpenAPI

        Args:
            field (FilterField):
            operator (str):
            values ([str]):
            item_type (int): ID of an item type
            sub_query (FilterQuery):
            rules ([FilterRule]):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", False)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (args, self.__class__.__name__,),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.field = field
        self.operator = operator
        self.values = values
        self.item_type = item_type
        self.sub_query = sub_query
        self.rules = rules
        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(
                    f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                    f"class with read only attributes."
                )
